trigger:
 - backend

resources:
 - repo: self

variables:
 tag: $(Build.BuildId)

stages:
 - stage: BuildAndPush
   displayName: Build and Push Docker Image
   jobs:
    - job: BuildAndPushImage
      displayName: Build and Push Image
      pool:
       vmImage: ubuntu-latest
      steps:
       - script: |
          echo "Building Docker image with tag: $(tag)"
          docker build --build-arg PORT=$(PORT) -f backend/Dockerfile -t joelwekesa/backend:$(tag) ./backend
         displayName: Build Docker Image
         env:
          DOCKER_BUILDKIT: 1

       - task: Docker@2
         inputs:
          containerRegistry: 'docker'
          repository: 'joelwekesa/backend'
          command: 'push'
          tags: '$(tag)'

       - script: |
          echo "Docker images list:"
          docker images
         displayName: List Docker Images

 - stage: DeployToEC2
   displayName: Deploy to EC2 Instance
   jobs:
    - job: DeployContainer
      displayName: Deploy Container to EC2
      pool:
       vmImage: ubuntu-latest
      steps:
       - task: SSH@0
         inputs:
          sshEndpoint: 'SIL'
          runOptions: 'commands'
          commands: |
           echo "Pulling Docker image: joelwekesa/backend:$(tag)"
           docker pull joelwekesa/backend:$(tag)
           docker stop backend 2>/dev/null || true
           docker rm backend 2>/dev/null || true
           docker network inspect app_network >/dev/null 2>&1 || docker network create app_network
           echo "Running Docker container: backend"
           docker run -d --name backend --network app_network -e DATABASE_URL=$(DATABASE_URL) -p 5001 joelwekesa/backend:$(tag)
         displayName: Deploy Backend Container
         timeoutInMinutes: 20
